### PR TITLE
Split files

### PR DESCRIPTION
**Pull request by ohinder**
Sorry I forgot to pull these changes.

### CODE REVIEW

**Comment by tiagoakle** [comment]
Did we conflict?

On Mon, Jan 26, 2015 at 11:06 AM, ohinder notifications@github.com wrote:

> Merged #3 https://github.com/copl/mpc_lp_julia/pull/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/copl/mpc_lp_julia/pull/3#event-224844876.

## 

Santiago Akle
+1 650 919 4833
tiagoakle@gmail.com

**Comment by tiagoakle** [comment]
@ohinder we have been working on two different files you made the folder
and I worked on the file lopt_c_style.jl
Lets use the meeting today to incorporate the changes I did in the file to
the folder and remove everything that is not relevant.
Some things I did were add a settings class.
we should normalize all the class names so that they start with
class_<name>. We don't need constructors really
but we are simulating c++ so ok.
We should use the Julia type system to enforce typed variables, this is
more C++ like.
Oh one more thing. There is no point in having two instances of the search
direction object, after the affine direction is known the combined can be
stored over it. This will in practice matter for larger problems.
Lets chat later today

On Mon, Jan 26, 2015 at 11:06 AM, Santiago Akle tiagoakle@gmail.com wrote:

> Did we conflict?
> 
> On Mon, Jan 26, 2015 at 11:06 AM, ohinder notifications@github.com
> wrote:
> 
> > Merged #3 https://github.com/copl/mpc_lp_julia/pull/3.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/copl/mpc_lp_julia/pull/3#event-224844876.
> 
> ## 
> 
> Santiago Akle
> +1 650 919 4833
> tiagoakle@gmail.com

## 

Santiago Akle
+1 650 919 4833
tiagoakle@gmail.com

**Comment by ohinder** [comment]
sorry about that. I made changes but forgot to upload them.

On Mon, Jan 26, 2015 at 11:12 AM, Santiago Akle notifications@github.com
wrote:

> @ohinder we have been working on two different files you made the folder
> and I worked on the file lopt_c_style.jl
> Lets use the meeting today to incorporate the changes I did in the file to
> the folder and remove everything that is not relevant.
> Some things I did were add a settings class.
> we should normalize all the class names so that they start with
> class_<name>. We don't need constructors really
> but we are simulating c++ so ok.
> We should use the Julia type system to enforce typed variables, this is
> more C++ like.
> Oh one more thing. There is no point in having two instances of the search
> direction object, after the affine direction is known the combined can be
> stored over it. This will in practice matter for larger problems.
> Lets chat later today
> 
> On Mon, Jan 26, 2015 at 11:06 AM, Santiago Akle tiagoakle@gmail.com
> wrote:
> 
> > Did we conflict?
> > 
> > On Mon, Jan 26, 2015 at 11:06 AM, ohinder notifications@github.com
> > wrote:
> > 
> > > Merged #3 https://github.com/copl/mpc_lp_julia/pull/3.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/copl/mpc_lp_julia/pull/3#event-224844876.
> > 
> > ## 
> > 
> > Santiago Akle
> > +1 650 919 4833
> > tiagoakle@gmail.com
> 
> ## 
> 
> Santiago Akle
> +1 650 919 4833
> tiagoakle@gmail.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/copl/mpc_lp_julia/pull/3#issuecomment-71518586.

## 

Thanks,
Oliver Hinder,

ohinder@gmail.com

**Comment by ohinder** [comment]
I am incorporating your changes now.

On Mon, Jan 26, 2015 at 11:12 AM, Santiago Akle notifications@github.com
wrote:

> @ohinder we have been working on two different files you made the folder
> and I worked on the file lopt_c_style.jl
> Lets use the meeting today to incorporate the changes I did in the file to
> the folder and remove everything that is not relevant.
> Some things I did were add a settings class.
> we should normalize all the class names so that they start with
> class_<name>. We don't need constructors really
> but we are simulating c++ so ok.
> We should use the Julia type system to enforce typed variables, this is
> more C++ like.
> Oh one more thing. There is no point in having two instances of the search
> direction object, after the affine direction is known the combined can be
> stored over it. This will in practice matter for larger problems.
> Lets chat later today
> 
> On Mon, Jan 26, 2015 at 11:06 AM, Santiago Akle tiagoakle@gmail.com
> wrote:
> 
> > Did we conflict?
> > 
> > On Mon, Jan 26, 2015 at 11:06 AM, ohinder notifications@github.com
> > wrote:
> > 
> > > Merged #3 https://github.com/copl/mpc_lp_julia/pull/3.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/copl/mpc_lp_julia/pull/3#event-224844876.
> > 
> > ## 
> > 
> > Santiago Akle
> > +1 650 919 4833
> > tiagoakle@gmail.com
> 
> ## 
> 
> Santiago Akle
> +1 650 919 4833
> tiagoakle@gmail.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/copl/mpc_lp_julia/pull/3#issuecomment-71518586.

## 

Thanks,
Oliver Hinder,

ohinder@gmail.com

**Pull request merged**
